version: "3.3"
services:
  postgresql:
    image: postgres:12.3
    environment:
      POSTGRES_PASSWORD: password
    restart: always
    ports:
      - 5432:5432
  django:
    image: pyappenv:latest
    environment:
      - DATABASE_URL=postgres://postgres:password@postgresql:5432/postgres 
      - CLIENT_ID="Rgkqb0nHHdZkE5LdiIGWspJaZ1OBurcudFISCpUO"
      - CLIENT_SECRET="A6x43GBwX1JWdQoKrkYX9SKoPX2Ws601WvFlf6hmnhslc3uZZMBEsK2wxR8I1eF6qQI6lsaGN8WztV0nPbFf28oZAkkPXebTvxQYCKP8AcvEVPOTb5a1ZirKGy5ryD9y"
      - REDIRECT_URI="http://localhost:3000/api/oauth-callback"
    restart: always
    ports:
      - "8000:8000"
    volumes:
        - ./:/app
    entrypoint: './manage.py'
    command: runserver 0.0.0.0:8000
    

